name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            
            echo "🧹 기존 배포 관련 프로세스 정리 중..."

            # 남아있는 배포 관련 프로세스 정리
            pkill -f 'zzirit-0.0.1-SNAPSHOT.jar' || true
            pkill -f 'git pull' || true
            pkill -f 'git fetch' || true
            pkill -f 'gradle' || true
            pkill -f 'bash -c cd ~/WEB4_5_AnjolinaJelly_BE' || true

            # git lock 제거
            rm -f ~/WEB4_5_AnjolinaJelly_BE/.git/index.lock || true

            echo "✅ 정리 완료"
            
            cd ~/WEB4_5_AnjolinaJelly_BE

            git pull origin main

            cd ~
            sudo systemctl stop nginx || true
            docker-compose -f docker-compose.nginx.yaml up -d

            cd ~/WEB4_5_AnjolinaJelly_BE
            docker-compose -f docker-compose.dev.yaml up -d
            
            ./gradlew build -x test # 테스트 제외해야 빌드 성공
            mv ./build/libs/zzirit-0.0.1-SNAPSHOT.jar ./src/main/resources/
            
            cd ./src/main/resources
            # java -jar zzirit-0.0.1-SNAPSHOT.jar
            nohup java -jar zzirit-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod > ../../../../log.txt 2>&1 &
